//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanAirportWebApp.Models.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int id { get; set; }
        public string login { get; set; }
        public string passWord { get; set; }
        public string email { get; set; }
        public Nullable<int> passengerId { get; set; }
        public int userTypeId { get; set; }
    }
}
