//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanAirportWebApp.Models.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypes
    {
        public int id { get; set; }
        public string typeName { get; set; }
    }
}
