// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace FlightsML
{
    public partial class DeparturesModel
    {
        /// <summary>
        /// model input class for DeparturesModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"dayTime")]
            public float DayTime { get; set; }

            [ColumnName(@"windSpeed")]
            public float WindSpeed { get; set; }

            [ColumnName(@"visibility")]
            public float Visibility { get; set; }

            [ColumnName(@"airPressure")]
            public float AirPressure { get; set; }

            [ColumnName(@"temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"airlineId")]
            public float AirlineId { get; set; }

            [ColumnName(@"cityId")]
            public float CityId { get; set; }

            [ColumnName(@"delayTime")]
            public float DelayTime { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DeparturesModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DeparturesModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
