﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Flights_ML
{
    public partial class ArrivalsModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"dayTime", @"dayTime"),new InputOutputColumnPair(@"windSpeed", @"windSpeed"),new InputOutputColumnPair(@"visibility", @"visibility"),new InputOutputColumnPair(@"airPressure", @"airPressure"),new InputOutputColumnPair(@"temperature", @"temperature"),new InputOutputColumnPair(@"airlineId", @"airlineId"),new InputOutputColumnPair(@"cityId", @"cityId")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"dayTime",@"windSpeed",@"visibility",@"airPressure",@"temperature",@"airlineId",@"cityId"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=869,MinimumExampleCountPerLeaf=4,NumberOfIterations=32,MaximumBinCountPerFeature=201,LearningRate=0.0476955255661842F,LabelColumnName=@"delayTime",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.89287093705067F,FeatureFraction=0.955603157697116F,L1Regularization=0.335963838239639F,L2Regularization=1.0601898503462E-09F}}));

            return pipeline;
        }
    }
}
