//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanAirportWebApp.Models.Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KazanAirportDbEntities : DbContext
    {
        public KazanAirportDbEntities()
            : base("name=KazanAirportDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airlines> Airlines { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<FlightStatuses> FlightStatuses { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
    }
}
